server:
  port: 8083

spring:
  application:
    name: envios-service
  profiles:
    active: ${SPRING_PROFILES_ACTIVE:azure}
  jpa:
    open-in-view: false

internal:
  token: ${INTERNAL_TOKEN}

management:
  endpoints:
    web:
      exposure:
        include: health,info
